### ISSUE TITLE
Suggest Idea and feature that make the project fit the theme of  `It's not a bug, it's a feature` 

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#13]

**Comment by Sushant-Padha** [comment]
Similar to the famous Nuclear Gandhi bug in Civilization II, we can introduce:

**Bug:** If the snake gets too long, its length inverts and its *head* is now at the *end* of its body (instead of the tail being at the end).

**Feature:** This feature of moving "head-last" allows the rest of the snake's body to overflow through the canvas, thus it easier to handle and it the player will have an easy time staying alive.

It sounds odd at first but if we include some signs and references to [Integer Overflow](https://en.wikipedia.org/wiki/Integer_overflow) and [Nuclear Gandhi](https://en.wikipedia.org/wiki/Nuclear_Gandhi) it can add to the game design.

**Comment by Anirban-Majumder** [comment]
Yes good idea we could look into implementing it Tomorrow after most of the frontend issues is fixed.

**Comment by Anirban-Majumder** [comment]
Reopen in issue #50
